import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}





// // app/layout.tsx
// import type { Metadata } from "next";
// import { Mochiy_Pop_One, Nunito } from "next/font/google";
// import "./globals.css";

// // ← Perfect daycare heading font (cute & bold)
// const mochiy = Mochiy_Pop_One({
//   weight: "400",
//   subsets: ["latin"],
//   variable: "--font-mochiy",
// });

// // ← Perfect readable body font for parents
// const nunito = Nunito({
//   weight: ["400", "600", "700"],
//   subsets: ["latin"],
//   variable: "--font-nunito",
// });

// export const metadata: Metadata = {
//   title: "Happy Little Learners Daycare",
//   description: "A warm and nurturing daycare for your child",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${mochiy.variable} ${nunito.variable} font-nunito antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
